users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.views.generic import TemplateView
from . import forms
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = 'users'

urlpatterns = [
    path("login/", views.LoginUser.as_view(), name="login"),

    path("logout/", LogoutView.as_view(), name="logout"),

    path("password-change/", views.UserPasswordChange.as_view(), name="password_change"),

    path("password-change/done/", PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'
    ), name="password_change_done"),

    path("password-reset/done/", PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name="password_reset_done"),

    path("password-reset/", PasswordResetView.as_view(
        form_class=forms.UserPasswordResetForm,
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')
    ), name="password_reset"),

    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            form_class=forms.UserPasswordResetConfirmForm,
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete')
        ),
        name="password_reset_confirm"
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name="password_reset_complete"
    ),
    path(
        "register-done/",
        TemplateView.as_view(template_name="users/register_done.html"),
        name="register_done"
    ),

    path("register/", views.RegisterUser.as_view(), name="register"),

    path("profile/", views.ProfileUser.as_view(), name="profile"),
]

velik/urls.py
from django.contrib import admin
from django.urls import path, include
from velik import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Велосипеды'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    photo = models.ImageField(
        upload_to="users/%Y/%m/%d/",
        blank=True,
        null=True,
        )

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, PasswordResetForm,SetPasswordForm
from django.contrib.auth import get_user_model


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={
                                   'class': 'form-input my-border form-control',
                                   'placeholder': 'Логин'
                               }))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={
                                   'class': 'form-input my-border form-control',
                                   'placeholder': 'Пароль',
                                   'type': 'password'
                               }))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={
                                   'class': 'form-input my-border form-control',
                                   'placeholder': 'Логин'
                               }))
    password1 = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={
                                   'class': 'form-input my-border form-control',
                                   'placeholder': 'Пароль',
                                   'type': 'password'
                               }))
    password2 = forms.CharField(label='Повтор пароля',
                                widget=forms.PasswordInput(attrs={
                                   'class': 'form-input my-border form-control',
                                   'placeholder': 'Повтор пароля',
                                   'type': 'password'
                               }))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.TextInput(attrs={
                                   'class': 'form-input my-border form-control',
                                   'placeholder': 'E-mail'
                               }),
            'first_name': forms.TextInput(attrs={
                                   'class': 'form-input my-border form-control',
                                   'placeholder': 'Имя'
                               }),
            'last_name': forms.TextInput(attrs={
                                   'class': 'form-input my-border form-control',
                                   'placeholder': 'Фамилия'
                               }),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Такой E-mail уже существует')
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(label='Логин',
                               disabled=True,
                               widget=forms.TextInput(attrs={
                                   'class': 'form-input my-border form-control',
                               }))
    email = forms.CharField(label='E-mail',
                            disabled=True,
                            widget=forms.TextInput(attrs={
                               'class': 'form-input my-border form-control',
                            }))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={
                                   'class': 'form-input my-border form-control',
                               }),
            'last_name': forms.TextInput(attrs={
                                   'class': 'form-input my-border form-control',
                               }),
        }


class UserPassworChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Старый пароль",
        widget=forms.TextInput(attrs={
                                   'class': 'form-input my-border form-control',
                                   'placeholder': 'Старый пароль',
                                   'type': 'password'
                               })
        )
    new_password1 = forms.CharField(
        label="Новый пароль",
        widget=forms.TextInput(attrs={
                                   'class': 'form-input my-border form-control',
                                   'placeholder': 'Новый пароль',
                                   'type': 'password'
                               })
        )
    new_password2 = forms.CharField(
        label="Подтверждение пароля",
        widget=forms.TextInput(attrs={
                                   'class': 'form-input my-border form-control',
                                   'placeholder': 'Повтор пароля',
                                   'type': 'password'
                               })
        )


class UserPasswordResetForm(PasswordResetForm):
    email = forms.CharField(label='E-mail',
                            widget=forms.TextInput(attrs={
                                'class': 'form-input my-border form-control',
                                'placeholder': 'E-mail'
                            }))

    class Meta:
        model = get_user_model()
        fields = ['email',]


class UserPasswordResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label="Новый пароль",
        widget=forms.TextInput(attrs={
                                   'class': 'form-input my-border form-control',
                                   'placeholder': 'Новый пароль',
                                   'type': 'password'
                               })
        )
    new_password2 = forms.CharField(
        label="Подтверждение пароля",
        widget=forms.TextInput(attrs={
                                   'class': 'form-input my-border form-control',
                                   'placeholder': 'Повтор пароля',
                                   'type': 'password'
                               })
        )

    class Meta:
        model = get_user_model()
        fields = ['new_password1', 'new_password2',]

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from users.forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPassworChangeForm
from django.views.generic import CreateView, UpdateView


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {
        'title': 'Авторизация'
    }


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {
        'title': 'Регистрация'
    }
    success_url = reverse_lazy('users:register_done')


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Профиль пользователя'}

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPassworChangeForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change_form.html'

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container">
    <div class="login-page">
        <div class="form my-border">
          <h1>Авторизация</h1>
          <form class="login-form" method="post">

            {% csrf_token %}
            <input type="hidden" name="next" value="{{next}}"/>
            <div class="form-error">
              {% if form.non_field_errors %}
              <ul class="errorlist nonfield">
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
              </ul>
              {% endif %}
            </div>
            
            {% for f in form %}
                {{ f }}
                <div class="form-error">
                  {% if f.errors %}
                  <ul class="errorlist nonfield">
                    {% for error in f.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                  </ul>
                  {% endif %}
                </div>
            {% endfor %}
                
            <button class="btn btn-primary" type="submit">Войти</button>
        
            <p class="message"><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
          </form>
        </div>
      </div>
</div>
{% endblock %}
    

users/templates/users/password-reset_complete.html
{% extends 'base.html' %}


{% block content %}

<h1>Пароль успешно изменен</h1>

<p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
     <a href="{% url 'users:login' %}">входа в систему</a>.</p>
{% endblock content %}
    

users/templates/users/password_change_done.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
    <div class="welcome">
      <h1>Пароль успешно изменен!</h1>
      <p>Вы успешно изменили пароль</p>
      <div class="button-welcome">
        <a href="{% url 'users:profile' %}">
          <button class="btn btn-outline-primary">
            Профиль
          </button>
        </a>
      </div>
    </div>
</div>
{% endblock content %}
    

users/templates/users/password_change_form.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container">
    <div class="login-page">
        <div class="form my-border">
          <h1>Изменение пароля</h1>
          <form class="login-form" method="post">

            {% csrf_token %}
            <div class="form-error">
              {% if form.non_field_errors %}
              <ul class="errorlist nonfield">
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
              </ul>
              {% endif %}
            </div>
            
            {% for f in form %}
                {{ f }}
                <div class="form-error">
                  {% if f.errors %}
                  <ul class="errorlist nonfield">
                    {% for error in f.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                  </ul>
                  {% endif %}
                </div>
            {% endfor %}
                
            <button class="btn btn-primary" type="submit">Изменить пароль</button>
          </form>
        </div>
      </div>
</div>
{% endblock %}
    
    

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
    <div class="welcome">
      <h1>Пароль успешно изменен!</h1>
      <p>Вы успешно изменили пароль<br>Используйте его для авторизации</p>
      <div class="button-welcome">
        <a href="{% url 'users:login' %}">
          <button class="btn btn-outline-primary">
            Авторизация
          </button>
        </a>
      </div>
    </div>
</div>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container">
    <div class="login-page">
        <div class="form my-border">
          <h1>Новый пароль</h1>
          <form class="login-form" method="post">

            {% csrf_token %}
            <div class="form-error">
              {% if form.non_field_errors %}
              <ul class="errorlist nonfield">
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
              </ul>
              {% endif %}
            </div>
            
            {% for f in form %}
                {{ f }}
                <div class="form-error">
                  {% if f.errors %}
                  <ul class="errorlist nonfield">
                    {% for error in f.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                  </ul>
                  {% endif %}
                </div>
            {% endfor %}
                
            <button class="btn btn-primary" type="submit">Сохранить</button>
          </form>
        </div>
      </div>
</div>
{% endblock %}
    

users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<div class="container">
    <div class="welcome">
      <h1>Сброс пароля</h1>
      <p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>
      <p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
    </div>
</div>
{% endblock content %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container">
    <div class="login-page">
        <div class="form my-border">
          <h1>Восстановление пароля</h1>
          <form class="login-form" method="post">

            {% csrf_token %}
            <div class="form-error">
              {% if form.non_field_errors %}
              <ul class="errorlist nonfield">
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
              </ul>
              {% endif %}
            </div>
            
            {% for f in form %}
                {{ f }}
                <div class="form-error">
                  {% if f.errors %}
                  <ul class="errorlist nonfield">
                    {% for error in f.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                  </ul>
                  {% endif %}
                </div>
            {% endfor %}
                
            <button class="btn btn-primary" type="submit">Cбросить по E-mail</button>
          </form>
        </div>
      </div>
</div>
{% endblock %}
    

users/templates/users/profile.html
{% extends 'base.html' %}
{%load catalog_tags%} 


{% block content %}
<div class="container">
    
    <div class="row d-flex pt-3 pb-5">
        <div class="col-0 col-lg-6"></div>
        <div class="bike-title col-12 col-lg-6 ps-3 pe-3 pb-3 border-bottom">
          <h1>Профиль</h1>
        </div>
        <!-- ----------------------------- -->
        <!-- нужно добавить смену аватарки -->
        <!-- ----------------------------- -->
        <div class="bike-img col-12 col-lg-6 pt-3 pe-3">
            {% if user.photo|find_image %}
                  <img class="d-block" src="{{ user.photo.url }}">
            {% else %}
                  <img class="d-block" src="{{ default_profile }}">
            {% endif %}
        </div>
        <div class="col-12 col-lg-6 p-3 border-bottom">
            <form class="" method="post">
                {% csrf_token %}
                <div class="form-error">
                    {% if form.non_field_errors %}
                    <ul class="errorlist nonfield">
                      {% for error in form.non_field_errors %}
                          <li>{{ error }}</li>
                      {% endfor %}
                    </ul>
                    {% endif %}
                  </div>
                
                {% for f in form %}
                    <p><label class="form-label" for="{{f.id_for_label}}">{{ f.label }}</label>{{ f }}</p>
                    <div class="form-error">
                        {% if f.errors %}
                        <ul class="errorlist nonfield">
                          {% for error in f.errors %}
                              <li>{{ error }}</li>
                          {% endfor %}
                        </ul>
                        {% endif %}
                      </div>
                {% endfor %}
            
                <div class="d-flex justify-content-center mb-3">
                    <button class="btn btn-primary" type="submit">Сохранить</button>
                </div>
            </form>
        </div>
        <div class="col-0 col-lg-6 p-lg-3"></div>
        <div class="col-12 col-lg-6 p-3">

            <p class="url-profile"><a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
            <p class="url-profile"><a href="{% url 'favourites' %}">Избранное</a></p>
            <p class="url-profile"><a href="{% url 'stars' %}">Мои оценки</a></p>
        </div>
    </div>

</div>
{% endblock content %}s
    

users/templates/users/register.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container">
    <div class="login-page">
        <div class="form my-border">
          <h1>Регистрация</h1>
          <form class="login-form" method="post">

            {% csrf_token %}
            <input type="hidden" name="next" value="{{next}}"/>
            <div class="form-error">
              {% if form.non_field_errors %}
              <ul class="errorlist nonfield">
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
              </ul>
              {% endif %}
            </div>
            
            {% for f in form %}
                {{ f }}
                <div class="form-error">
                  {% if f.errors %}
                  <ul class="errorlist nonfield">
                    {% for error in f.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                  </ul>
                  {% endif %}
                </div>
            {% endfor %}
                
            <button class="btn btn-primary" type="submit">Регистрация</button>
          </form>
        </div>
      </div>
</div>
{% endblock %}
    

users/templates/users/register_done.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container">
    <div class="welcome">
      <h1>Добро пожаловать!</h1>
      <p>Вы успешно зарегистрировались на сайте!<br>Для входа в систему необходимо авторизоваться</p>
      <div class="button-welcome">
        <a href="{% url 'users:login' %}">
          <button class="btn btn-outline-primary">
            Авторизация
          </button>
        </a>
      </div>
    </div>
</div>
    
{% endblock %}
    