users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.views.generic import TemplateView
from . import forms
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = 'users'

urlpatterns = [
    path("login/", views.LoginUser.as_view(), name="login"),

    path("logout/", LogoutView.as_view(), name="logout"),

    path("password-change/", views.UserPasswordChange.as_view(), name="password_change"),

    path("password-change/done/", PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'
    ), name="password_change_done"),

    path("password-reset/done/", PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name="password_reset_done"),

    path("password-reset/", PasswordResetView.as_view(
        form_class=forms.UserPasswordResetForm,
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')
    ), name="password_reset"),

    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            form_class=forms.UserPasswordResetConfirmForm,
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete')
        ),
        name="password_reset_confirm"
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name="password_reset_complete"
    ),
    path(
        "register-done/",
        TemplateView.as_view(template_name="users/register_done.html"),
        name="register_done"
    ),

    path("register/", views.RegisterUser.as_view(), name="register"),

    path("profile/", views.ProfileUser.as_view(), name="profile"),
]

velik/urls.py
from django.contrib import admin
from django.urls import path, include
from velik import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Велосипеды'

templates/base.html
{% load static %}
{% load catalog_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ title }}</title>
    <link
      type="text/css"
      href="{% static 'catalog/css/styles.css' %}"
      rel="stylesheet"
    />
    <link
      type="text/css"
      href="{% static 'users/css/styles.css' %}"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="{% static 'catalog/images/favicon_io/apple-touch-icon.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="{% static 'catalog/images/favicon_io/favicon-32x32.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="{% static 'catalog/images/favicon_io/favicon-16x16.png' %}"
    />
    <link
      rel="manifest"
      href="{% static 'catalog/images/favicon_io/site.webmanifest' %}"
    />
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">
            <img
              class="navbar-logo"
              width="64"
              src="{% static 'catalog/images/logo.svg' %}"
            />
          </a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% for item in main_menu %}
              <li class="nav-item item-navbar">
                {% if title == item.title %}
                <a class="nav-link active" href="{% url item.url %}"
                  >{{ item.title }}</a
                >
                {% else %}
                <a class="nav-link" href="{% url item.url %}"
                  >{{ item.title }}</a
                >
                {% endif %}
              </li>
              {% endfor %}
            </ul>

            
            {% if user.is_authenticated %}
            <a class="profile-link" href="{% url 'users:profile' %}">
              <div class="d-flex align-items-center">
                  <p class="username item-navbar">{{ user.username }}</p>
                  
                  {% if user.photo|find_image %}
                  <img class="item-navbar" width="50" src="{{ user.photo.url }}">
                  {% else %}
                  <img class="item-navbar" width="50" src="{{ default_profile }}">
                  {% endif %}
                    
              </div>
            </a>
            <div class="d-flex">
              <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-primary item-navbar btn-right">
                  Выйти
                </button>
              </form>
            </div>
            {% else %}
            <div class="d-flex">
              <a href="{% url 'users:register' %}">
                <button class="btn btn-outline-primary item-navbar">
                  Регистрация
                </button>
              </a>
            </div>
            <div class="d-flex">
              <a href="{% url 'users:login' %}">
                <button class="btn btn-primary item-navbar btn-right">
                  Войти
                </button>
              </a>
            </div>
            {% endif %}
              

          </div>
        </div>
      </nav>
      {% block content %} {% endblock %}

      <div class="container-fluid footer">
        <div class="row">
          <div class="col-6">
            <ul class="nav flex-column">
              <a class="navbar-brand" href="{% url 'home' %}">
                <img
                  class="navbar-logo"
                  width="64"
                  src="{% static 'catalog/images/logo.svg' %}"
                />
              </a>
              <div class="text-box-footer">
                <p class="text-footer-grey">
                  2025 <br />
                  Катайся в удовольствие
                </p>
              </div>
            </ul>
          </div>

          <div class="col-6">
            <div class="d-flex justify-content-end">
              <ul class="nav flex-column">
                <li class="nav-item">
                  {% for item in main_menu %} {% if forloop.counter0|divisibleby:2%}
                  <a
                    href="{% url item.url %}"
                    class="nav-link item-footer-grey footer-menu"
                    >{{ item.title }}</a
                  >
                  {% else %}
                  <a
                    href="{% url item.url %}"
                    class="nav-link item-footer-orange footer-menu"
                    >{{ item.title }}</a
                  >
                  {% endif %} {% endfor %}
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="d-flex justify-content-center py-4 my-4 border-top">
        <p class="text-footer-grey">2025 Разработано в учебных целях.</p>
        <p class="text-footer-orange">&nbspVelik.</p>
      </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
      var currentUrl = $(location).attr('href');
      var black_heart = "{% static 'catalog/images/black_heart.svg' %}";
      var grad_heart = "{% static 'catalog/images/grad_heart.svg' %}";
      var black_star = "{% static 'catalog/images/black_star.svg' %}";
      var grad_star = "{% static 'catalog/images/grad_star.svg' %}";
      var login_url = "{% url 'users:login' %}?next={{request.path}}";
    </script>
    <script type="text/javascript" src="{% static 'catalog/js/add_del_favorites.js' %}"></script>
    <script type="text/javascript" src="{% static 'catalog/js/add_update_stars.js' %}"></script>
    <script type="text/javascript" src="{% static 'catalog/js/delete_stars.js' %}"></script>
    <script type="text/javascript" src="{% static 'catalog/js/bike_functions.js' %}"></script>
  </body>
</html>